# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HMcPsxf0UpANBT1SiIuUZsF54aEzI82A
"""

import pandas as pd
import datetime
import numpy as np
import re
import logging
import importlib
import data_clean
import sqlite3
import utils
from sqlalchemy import create_engine, inspect

importlib.reload(data_clean)

df = pd.read_csv(
    "https://raw.githubusercontent.com/JackyP/testing/master/datasets/nycflights.csv",
    index_col=0
    )

df_raw = data_clean.remove_colunas(df)

df_raw = data_clean.rename_colunas(df_raw)

df_raw = data_clean.def_type_str(df_raw, ["id_voo"])

df_raw_clean = data_clean.ajusta_campo(df_raw, ["companhia", "id_voo", "origem", "destino"])

df_raw_horas_voo = tempo_voo_horas(df_raw_clean, "tempo_voo")

df_transformed = turno_partida(df_raw_horas_voo, "data_hora")

con = sqlite3.connect('projeto_python.db')
cur = con.cursor()
engine = create_engine("sqlite:///projeto_python.db")

with engine.connect() as connection:
    df_transformed.to_sql(name='flights', con=connection, index=False, if_exists='append')

cur.execute('SELECT * from flights limit 10')
result = cur.fetchall()
print(result)

#!pip freeze > requirements.txt
